# Generated by Django 5.1.15 on 2026-09-08 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioclubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(default='EA1RKV', help_text='Club callsign', max_length=20)),
                ('club_name', models.CharField(default='Unión de Radioafeccionados de Vigo-Val Miñor', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('locator', models.CharField(blank=True, help_text='Maidenhead grid locator (e.g., IN52JD)', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Radioclub Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL')),
                ('twitter', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('youtube', models.URLField(blank=True, help_text='YouTube channel URL')),
                ('qrz', models.URLField(blank=True, help_text='QRZ.com profile URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Social Media Settings',
            },
        ),
    ]
