# Generated by Django 5.1.15 on 2026-09-08 21:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, help_text='Escribe y da formato al texto; puedes insertar imágenes y enlaces desde la barra de herramientas.', verbose_name='Contenido'),
        ),
    ]
