# Generated by Django 5.1.15 on 2026-09-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_convert_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='comments_enabled',
            field=models.BooleanField(default=False, verbose_name='Permitir comentarios'),
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre o indicativo')),
                ('text', models.TextField(max_length=3000, verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], db_index=True, default='pending', max_length=10, verbose_name='Estado')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to='blog.blogpage', verbose_name='Entrada')),
            ],
            options={
                'verbose_name': 'Comentario del blog',
                'verbose_name_plural': 'Comentarios del blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
