# Generated by Django 5.1.15 on 2026-10-10 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpage_comments_enabled_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='announce_telegram',
            field=models.BooleanField(default=False, help_text='Sólo en la primera publicación en español. Las actualizaciones no generan anuncios.', verbose_name='Anunciar en Telegram'),
        ),
        migrations.CreateModel(
            name='TelegramDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_attempt', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('message_id', models.BigIntegerField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=200)),
                ('chat_id', models.CharField(max_length=200)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpage')),
            ],
        ),
    ]
