# Generated by Django 5.1.15 on 2026-09-09 10:47

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallsignsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Presentación')),
            ],
            options={
                'verbose_name': 'Indicativos especiales',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Presentación')),
            ],
            options={
                'verbose_name': 'Servicios del radioclub',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('kind', models.CharField(choices=[('repeater', 'Repetidores'), ('frequency', 'Frecuencias'), ('equipment', 'Equipos de radio'), ('other', 'Otros servicios')], default='repeater', max_length=20, verbose_name='Tipo')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Resumen')),
                ('content', wagtail.fields.RichTextField(blank=True, verbose_name='Descripción y condiciones de uso')),
                ('frequency', models.CharField(blank=True, max_length=80, verbose_name='Frecuencia / salida del repetidor (MHz)')),
                ('input_frequency', models.CharField(blank=True, max_length=80, verbose_name='Entrada del repetidor (MHz)')),
                ('mode', models.CharField(blank=True, max_length=80, verbose_name='Modo')),
                ('access', models.CharField(blank=True, max_length=150, verbose_name='Tono o parámetros de acceso')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación / cobertura')),
                ('equipment', models.CharField(blank=True, max_length=150, verbose_name='Modelo de equipo')),
                ('availability', models.CharField(blank=True, max_length=150, verbose_name='Estado / disponibilidad')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Fotografía')),
            ],
            options={
                'verbose_name': 'Servicio / recurso',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpecialCallsignPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('callsign', models.CharField(max_length=30, verbose_name='Indicativo')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Resumen de la actividad')),
                ('content', wagtail.fields.RichTextField(blank=True, verbose_name='Información de la actividad y QSL')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('qrz_url', models.URLField(blank=True, verbose_name='Página en QRZ')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Portada / diploma')),
            ],
            options={
                'verbose_name': 'Indicativo especial',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CallsignPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Pie de foto')),
                ('credit', models.CharField(blank=True, max_length=300, verbose_name='Autor / créditos')),
                ('group', models.CharField(blank=True, help_text='Las fotos con el mismo nombre se muestran juntas.', max_length=100, verbose_name='Álbum o grupo (opcional)')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Imagen')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='club.specialcallsignpage')),
            ],
            options={
                'verbose_name': 'Fotografía del indicativo',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
