# Generated by Django 5.1.15 on 2026-09-09 13:35

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialcallsignpage',
            name='award_rules',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Bases del diploma'),
        ),
        migrations.AddField(
            model_name='specialcallsignpage',
            name='bands',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bandas'),
        ),
        migrations.AddField(
            model_name='specialcallsignpage',
            name='layout',
            field=models.CharField(choices=[('activity', 'Actividad: información primero'), ('award', 'Diploma: bases primero'), ('report', 'Reportaje: fotografías primero')], default='activity', help_text='Elige un diseño ya preparado. Puedes cambiarlo sin perder contenido.', max_length=20, verbose_name='Plantilla de presentación'),
        ),
        migrations.AddField(
            model_name='specialcallsignpage',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lugar / locator'),
        ),
        migrations.AddField(
            model_name='specialcallsignpage',
            name='modes',
            field=models.CharField(blank=True, max_length=200, verbose_name='Modos'),
        ),
        migrations.AddField(
            model_name='specialcallsignpage',
            name='qsl_information',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Cómo solicitar la QSL'),
        ),
        migrations.AddField(
            model_name='specialcallsignpage',
            name='schedule',
            field=models.CharField(blank=True, help_text='Indica si los horarios son UTC o locales.', max_length=200, verbose_name='Horario y zona horaria'),
        ),
        migrations.CreateModel(
            name='CallsignDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.document', verbose_name='Documento')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='club.specialcallsignpage')),
            ],
            options={
                'verbose_name': 'Documento del indicativo',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
