# Generated by Django 5.1.15 on 2026-09-09 14:12

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_specialcallsignpage_award_rules_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallsignMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('kind', models.CharField(choices=[('document', 'Documentos'), ('image', 'Imágenes'), ('video', 'Vídeos'), ('audio', 'Audio'), ('youtube', 'YouTube')], default='image', max_length=20, verbose_name='Tipo de contenido')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Se muestra siempre junto al contenido, sin abrir desplegables.', verbose_name='Descripción')),
                ('group', models.CharField(blank=True, help_text='Usa el mismo nombre para agrupar varios elementos.', max_length=100, verbose_name='Grupo / álbum')),
                ('credit', models.CharField(blank=True, max_length=300, verbose_name='Autor / créditos')),
                ('youtube_url', models.URLField(blank=True, help_text='Pega el enlace al vídeo, no el código de inserción.', verbose_name='Enlace de YouTube')),
                ('asset', models.ForeignKey(blank=True, help_text='Sube o elige el archivo. Vídeo: MP4, WebM o M4V. Audio: MP3, WAV, OGG, M4A o FLAC.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtaildocs.document', verbose_name='Archivo (documento, vídeo o audio)')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Imagen')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='club.specialcallsignpage')),
            ],
            options={
                'verbose_name': 'Contenido de la biblioteca',
                'verbose_name_plural': 'Contenidos de la biblioteca',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
