# Generated by Django 5.1.15 on 2026-09-08 21:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='EA1RKV', help_text='Main heading displayed in the hero section', max_length=200)),
                ('hero_subtitle', models.CharField(default='Unión de Radioafeccionados de Vigo-Val Miñor', help_text='Subtitle displayed below the hero heading', max_length=300)),
                ('hero_cta_text', models.CharField(blank=True, default='Conoce el radioclub', help_text='Call-to-action button text', max_length=50)),
                ('hero_cta_url', models.CharField(blank=True, help_text='Call-to-action button URL', max_length=500)),
                ('about_title', models.CharField(default='Nuestro radioclub', max_length=200)),
                ('about_text', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('cards', 12), ('cta', 16), ('quote', 17), ('embed', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'required': True}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link for the card', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 7), ('image', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('cards', 11)]], {}), 13: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 15: ('wagtail.blocks.URLBlock', (), {'required': True}), 16: ('wagtail.blocks.StructBlock', [[('text', 13), ('button_text', 14), ('button_url', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('text', 7), ('author', 5)]], {}), 18: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media'})})),
                ('hero_image', models.ForeignKey(blank=True, help_text='Background image for the hero section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Home Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
