# Generated by Django 5.1.15 on 2026-09-08 21:36

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, help_text='Escribe y da formato al texto; puedes insertar imágenes y enlaces desde la barra de herramientas.', verbose_name='Contenido'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image_credit',
            field=models.CharField(blank=True, help_text='Autor, fuente y licencia, si corresponde.', max_length=300, verbose_name='Créditos de la imagen'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Sube la fotografía de Vigo que quieras mostrar. Puedes cambiarla en cualquier momento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Imagen de cabecera'),
        ),
    ]
