# Generated by Django 5.1.15 on 2026-09-08 21:22

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Members Directory',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('callsign', models.CharField(help_text='Amateur radio callsign', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short biography')),
                ('qrz_url', models.URLField(blank=True, help_text='QRZ.com profile URL')),
                ('is_board_member', models.BooleanField(default=False, help_text='Is this member part of the board of directors?')),
                ('role', models.CharField(blank=True, help_text='Role in the club (e.g., President, Secretary)', max_length=100)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='members.memberindexpage')),
            ],
            options={
                'verbose_name': 'Member',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
