# Generated by Django 5.1.15 on 2026-09-15 09:09

import django.db.models.deletion
import ea1rkv.apps.members.private
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDocumentsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Introducción')),
            ],
            options={
                'verbose_name': 'Documentación para socios',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ClubDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('category', models.CharField(default='Actas', max_length=100, verbose_name='Categoría')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(storage=ea1rkv.apps.members.private.PrivateStorage(), upload_to=ea1rkv.apps.members.private.private_upload, verbose_name='Archivo privado')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_documents', to='members.clubdocumentspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
