# Generated by Django 5.1.15 on 2026-09-15 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_clubdocumentspage_clubdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubdocument',
            name='download_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
