# Generated by Django 5.1.15 on 2026-09-15 13:17

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_clubdocument_download_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDownloadEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('confirmed_member', models.BooleanField(default=True, verbose_name='Confirmó ser socio')),
                ('first_download_at', models.DateTimeField(auto_now_add=True, verbose_name='Primera descarga')),
                ('last_download_at', models.DateTimeField(auto_now=True, verbose_name='Última descarga')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Número de descargas')),
                ('last_document', models.CharField(blank=True, max_length=200, verbose_name='Último documento')),
            ],
            options={
                'verbose_name': 'Correo de descarga',
                'verbose_name_plural': 'Correos de descargas',
                'ordering': ['-last_download_at'],
            },
        ),
        migrations.AddField(
            model_name='clubdocumentspage',
            name='privacy_notice',
            field=wagtail.fields.RichTextField(blank=True, default='<p>Guardaremos tu correo para registrar el acceso a la documentación del club. Puedes solicitar su consulta o eliminación contactando con el radioclub.</p>', verbose_name='Información sobre el uso del correo'),
        ),
    ]
