# Generated by Django 5.1.15 on 2026-09-08 21:22

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Events Index',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event_type', models.CharField(choices=[('contest', 'Contest'), ('field_day', 'Field Day'), ('meeting', 'Meeting'), ('workshop', 'Workshop'), ('social', 'Social Event'), ('other', 'Other')], default='other', max_length=20)),
                ('start_date', models.DateField(help_text='Event start date')),
                ('end_date', models.DateField(blank=True, help_text='Event end date (leave blank for single-day events)', null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('locator', models.CharField(blank=True, help_text='Maidenhead grid locator for the event location', max_length=10)),
                ('frequency', models.CharField(blank=True, help_text='Operating frequencies (e.g., 7.090 MHz, 144.300 MHz)', max_length=100)),
                ('mode', models.CharField(blank=True, help_text='Operating modes (e.g., SSB, CW, FT8)', max_length=100)),
                ('intro', models.TextField(help_text='Brief event description for listings', max_length=500)),
                ('body', wagtail.fields.StreamField([('heading', 2), ('paragraph', 3), ('image', 6), ('cards', 12), ('cta', 16), ('quote', 17), ('embed', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')]}), 2: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 1)]], {}), 3: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('attribution', 5)]], {}), 7: ('wagtail.blocks.TextBlock', (), {'required': True}), 8: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 9: ('wagtail.blocks.URLBlock', (), {'help_text': 'Optional link for the card', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('text', 7), ('image', 8), ('link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('cards', 11)]], {}), 13: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 50, 'required': True}), 15: ('wagtail.blocks.URLBlock', (), {'required': True}), 16: ('wagtail.blocks.StructBlock', [[('text', 13), ('button_text', 14), ('button_url', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('text', 7), ('author', 5)]], {}), 18: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media'})})),
                ('header_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Event',
                'ordering': ['-start_date'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
