# Generated by Django 5.1.15 on 2026-09-14 20:40

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventindexpage',
            options={'verbose_name': 'Agenda'},
        ),
        migrations.AlterModelOptions(
            name='eventpage',
            options={'ordering': ['-start_date'], 'verbose_name': 'Actividad'},
        ),
        migrations.AddField(
            model_name='eventpage',
            name='content',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_type',
            field=models.CharField(choices=[('contest', 'Concurso'), ('field_day', 'Actividad al aire libre'), ('meeting', 'Reunión'), ('workshop', 'Taller'), ('social', 'Encuentro social'), ('other', 'Otra actividad')], default='other', max_length=20),
        ),
    ]
