# Generated by Django 5.1.15 on 2026-09-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventindexpage_options_alter_eventpage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='recurrence',
            field=models.CharField(choices=[('none', 'No se repite'), ('monthly_nth', 'Mensual: día de la semana')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='recurrence_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='recurrence_week',
            field=models.PositiveSmallIntegerField(choices=[(1, 'primero'), (2, 'segundo'), (3, 'tercero'), (4, 'cuarto'), (5, 'último')], default=1),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='recurrence_weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'lunes'), (1, 'martes'), (2, 'miércoles'), (3, 'jueves'), (4, 'viernes'), (5, 'sábado'), (6, 'domingo')], default=4),
        ),
    ]
